### ISSUE TITLE
Belga scraping

### ISSUE THREAD

**Issue by inelstrom** [FleurJ/newsroom#24]
- Title

[h3 --> article title]

- Body:

[p/&-quot; --> body]
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">
 <br style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;">
  Une formation civile des imams francophones commencera &agrave; partir de l'ann&eacute;e acad&eacute;mique 2020-2021 &agrave; l'UCLouvain, a annonc&eacute; vendredi le ministre de la Justice, Koen Geens. Un accord a &eacute;t&eacute; conclu &agrave; ce sujet sous l'&eacute;gide du ministre entre l'universit&eacute; et l'AFOR (Acad&eacute;mie de formation et de recherche en &eacute;tudes islamiques), asbl cr&eacute;&eacute;e en collaboration avec l'Ex&eacute;cutif des Musulmans de Belgique (EMB).<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">La commission parlementaire d'enqu&ecirc;te sur les attentats du 22 mars 2016 et la mont&eacute;e du radicalisme avait conclu &agrave; la n&eacute;cessit&eacute; d'une formation universitaire des personnes souhaitant devenir ministre du culte islamique. En octobre 2017, dans son 4e rapport, elle
 avait recommand&eacute; &quot;que la formation de ces repr&eacute;sentants du culte soit approfondie, par la cr&eacute;ation d'un authentique cursus menant &agrave; l'exercice de ces professions&quot;.</br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">     &quot;Leur exercice devrait, en outre, id&eacute;alement &ecirc;tre subordonn&eacute; &agrave; la ma&icirc;trise d'au moins une des langues nationales, et &agrave; la connaissance des valeurs fondamentales de l'&Eacute;tat belge et des principes de droit en r&eacute;sultant&quot;, ajoutait-elle.</br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">   La formation des imams comportera deux volets, l'un th&eacute;ologique, l'autre civil, organis&eacute;s en parall&egrave;le. Le volet th&eacute;ologique est pris en charge par l'AFOR. L'universit&eacute; n&eacute;o-louvaniste se chargera du volet civil qui comprendra deux certificats. </br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">   Le premier, Religions et soci&eacute;t&eacute;s, couvrira l'introduction &agrave; la psychologie sociale, la sociologie religieuse, la la&iuml;cit&eacute; et la s&eacute;cularisation de la soci&eacute;t&eacute; ainsi que l'histoire. Le second, &quot;Islam et vivre-ensemble&quot;, vise &agrave; une meilleure connaissance de la diversit&eacute; belge et porte sur les droits de l'homme, le discours religieux sur internet, etc.</br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">   Cette formation civile devrait s'&eacute;tendre sur 4 ou 5 ans.</br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">   &quot;L'objectif est de proposer une formation solide pour comprendre les enjeux du pluralisme religieux&quot;, a expliqu&eacute; Louis-Leon Christians, professeur &agrave; l'UCLouvain, dans un communiqu&eacute;.</br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">   Cette formation sera ouverte non seulement aux futurs imams, pr&eacute;dicateurs, conseillers islamiques, etc. mais &eacute;galement &agrave; toute personne int&eacute;ress&eacute;e par le fait religieux.</br>
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">   &quot;La formation des imams est un grand pas dans le parcours d'institutionnalisation de l'Islam en Belgique. Nous esp&eacute;rons pouvoir servir notre communaut&eacute; &agrave; travers ce projet et bien d'autres dans le futur afin d'apporter notre pierre &agrave; l'&eacute;difice pour une institutionnalisation de l'Islam pleinement r&eacute;ussie et qui s'inscrit parfaitement dans le contexte de notre pays&quot;, a soulign&eacute; de son c&ocirc;t&eacute; le pr&eacute;sident de l'AFOR, Salah Echallaoui.</br>

- Publication date

[p, strong --> lieu, DATE, heure]
<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;">
<strong style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;">BRUXELLES 31/01 16:15 (BELGA)</strong>

- Suggested keywords:

<p style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6;"><strong style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;">Keywords:</strong><br style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;">
                BRIEF / GVTFED / RELIGION / ENSEIGNEMENT / JUSTICE / SHORT</p>

**Comment by FleurJ** [comment]
fichier html exemple : https://drive.google.com/open?id=1GCx-4KDjymVJAT5YqtQ5b06ALusOTXki

**Comment by FleurJ** [comment]
> **Keywords:**
> BRIEF / GVTFED / RELIGION / ENSEIGNEMENT / JUSTICE / SHORT

On peut laisser tomber les keywords, ce sont ceux de Belga, on en utilise d'autres à nous

**Comment by FleurJ** [comment]
> * Publication date
> 
> [p, strong --> lieu, DATE, heure]
> 
> **BRUXELLES 31/01 16:15 (BELGA)**

Plutôt que d'extraire la date de là qui est mélangée au lieu et à l'heure, on peut mettre par défaut la date du scrapping/création du brouillon.
